name: SilentJoin
main: com.frostcraft.silentjoin.SilentJoin
version: 1.1
commands:
permissions:
    silentjoin:
        description: permission for silent join, join messages.
        default: op
    silentquit:
        description: permission for silent join, quit messages.
        default: op